/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.adsb.client.gui.stca;

//import static Common.SelectMapSetup.isShowing;

import com.attech.adsb.client.common.Common;
import com.attech.adsb.client.common.MLogger;
import com.attech.adsb.client.common.NumericFilter;
import com.attech.adsb.client.common.Validator;
import com.attech.adsb.client.config.Configuration;
import com.attech.adsb.client.config.STCAConfig;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;


/**
 *
 * @author dungnt
 */
public class WarningEditorDlg extends javax.swing.JDialog {
    
    private static final MLogger logger = MLogger.getLogger(WarningEditorDlg.class);
    
    public static int indexVerMin = 0;
    public static int indexVerCus = 0;
    public static int indexHorMin = 0;
    public static int indexHorCus = 0;
    public static boolean isShowing;
    private final Color errorColor = Color.decode("0xffb3b3");
    private final Color originBackgroundColor;
    private Float [] horizonSteps = new Float [] { 3.0f, 5.0f, 10.0f };
    private Float [] verticalSteps = new Float [] { 1000.0f, 2000.0f };
    private int maxHorizonCount = 10;
    private int maxVerticalCount = 4000;
    
    
    
    /**
     * Creates new form SelectWarningSetup
     * @param parent
     * @param modal
     */
    public WarningEditorDlg(java.awt.Frame parent, boolean modal, STCAConfig config) {
        super(parent, modal);
        initComponents();
        originBackgroundColor = this.txtTime.getBackground();
        ((AbstractDocument) txtTime.getDocument()).setDocumentFilter(new NumericFilter(3));
//        cboHorCus.removeAllItems();
//        for (int i = Integer.parseInt(cboHorMin.getSelectedItem().toString()); i <= Integer.parseInt(cboHorMin.getSelectedItem().toString()) + 10; i++) {
//            cboHorCus.addItem(i);
//        }
//        cboVerCus.removeAllItems();
//        for (int i = 0; i <= 4; i++) {
//            cboVerCus.addItem(Integer.parseInt(cboVerMin.getSelectedItem().toString()) + i * 500);
//        }
//        cboHorMin.setSelectedIndex(indexHorMin);
//        cboHorCus.setSelectedIndex(indexHorCus);
//        cboVerMin.setSelectedIndex(indexVerMin);
//        cboVerCus.setSelectedIndex(indexVerCus);

        //btnOk.setText(Parameter.WarningHitDistance+ " " +Parameter.TriangleRegion+ " " +Parameter.WarningHitLevel);
        bind(config);
    }
    
    private void bind(STCAConfig config) {
        this.cboHorMin.setSelectedItem(Integer.toString(config.getHorizonAlarmThreshold()));
        this.cboHorCus.setSelectedItem(config.getHorizonWarnThreshold());
        this.cboVerMin.setSelectedItem(Integer.toString(config.getVerticalAlarmThreshold()));
        this.cboVerCus.setSelectedItem(config.getVerticalWarnThreshold());
        this.txtTime.setText(Integer.toString(config.getWarningTimeInAdvance()));
    }
    
    private boolean validateForm() {
        if (Validator.isNullOrEmpty(txtTime.getText())) {
            this.setError(txtTime);
        }
        
//        Float horizonMin = (Float) this.cboHorMin.getSelectedItem();
//        Float horizonCust = (Float) this.cboHorCus.getSelectedItem();
//        Float verticalMin  = (Float) this.cboVerMin.getSelectedItem();
//        Float verticalCust = (Float) this.cboVerCus.getSelectedItem();
//        
//        if (horizonMin < horizonCust) {
//            this.cboHorCus.setBackground(errorColor);
//        }
        return true;
    }
    
    private void clearError() {
        this.txtTime.setBackground(originBackgroundColor);
    }
    
    private void setError(JTextField textfield) {
        textfield.setBackground(errorColor);
        textfield.requestFocus();
    }
    
    private STCAConfig parse() {
        STCAConfig config = new STCAConfig();
        config.setHorizonAlarmThreshold(Integer.parseInt(cboHorMin.getSelectedItem().toString()));
        config.setHorizonWarnThreshold(Integer.parseInt(cboHorCus.getSelectedItem().toString()));
        config.setVerticalAlarmThreshold(Integer.parseInt(cboVerMin.getSelectedItem().toString()));
        config.setVerticalWarnThreshold(Integer.parseInt(cboVerCus.getSelectedItem().toString()));
        config.setWarningTimeInAdvance(Integer.parseInt(txtTime.getText()));
        return config;
    }
     
    @Override
    public void setVisible(boolean value) {
        isShowing = value;
        super.setVisible(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboHorMin = new JComboBox<Float>();
        cboHorCus = new JComboBox<Float>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboVerMin = new JComboBox<Float>();
        cboVerCus = new JComboBox<Float>();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Warning setup");
        setMaximumSize(new java.awt.Dimension(350, 300));
        setMinimumSize(new java.awt.Dimension(350, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Horizontal Separation");

        jLabel2.setText("Minimum");

        jLabel4.setText("Customisation");

        cboHorMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "10" }));
        cboHorMin.setMaximumSize(new java.awt.Dimension(120, 24));
        cboHorMin.setMinimumSize(new java.awt.Dimension(120, 24));
        cboHorMin.setPreferredSize(new java.awt.Dimension(120, 24));
        cboHorMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHorMinActionPerformed(evt);
            }
        });

        cboHorCus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "10" }));
        cboHorCus.setMaximumSize(new java.awt.Dimension(120, 24));
        cboHorCus.setMinimumSize(new java.awt.Dimension(120, 24));
        cboHorCus.setPreferredSize(new java.awt.Dimension(120, 24));

        jLabel3.setText("Nm");

        jLabel5.setText("Nm");

        jLabel8.setText("Vertical Separation");

        jLabel7.setText("Minimum");

        jLabel9.setText("Customisation");

        cboVerMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000", "2000" }));
        cboVerMin.setMaximumSize(new java.awt.Dimension(120, 24));
        cboVerMin.setMinimumSize(new java.awt.Dimension(120, 24));
        cboVerMin.setPreferredSize(new java.awt.Dimension(120, 24));
        cboVerMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVerMinActionPerformed(evt);
            }
        });

        cboVerCus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000", "1500", "2000", "2500", "3000", " " }));
        cboVerCus.setMaximumSize(new java.awt.Dimension(120, 24));
        cboVerCus.setMinimumSize(new java.awt.Dimension(120, 24));
        cboVerCus.setPreferredSize(new java.awt.Dimension(120, 24));

        jLabel10.setText("Ft");

        jLabel6.setText("Ft");

        jLabel11.setText("Warning time in adance");

        txtTime.setMaximumSize(new java.awt.Dimension(120, 24));
        txtTime.setMinimumSize(new java.awt.Dimension(120, 24));
        txtTime.setPreferredSize(new java.awt.Dimension(120, 24));

        jLabel12.setText("Seconds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboVerCus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboVerMin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHorCus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHorMin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboHorMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboHorCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboVerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboVerCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            this.dispose();
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {

            clearError();
            if (!this.validateForm()) {
                return;
            }
            
            int confirmed = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to save?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (confirmed != JOptionPane.YES_OPTION) {
                return;
            }
            STCAConfig config = this.parse();
            Configuration.instance().getStcaConfig().update(config);
            Configuration.instance().getStcaConfig().save(Common.CFG_STCA);
            this.dispose();
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnOkActionPerformed
    
    private void cboHorMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHorMinActionPerformed
        try {
            cboHorCus.removeAllItems();
            Integer horizonMin = Integer.parseInt(this.cboHorMin.getSelectedItem().toString());
            for (int i = horizonMin; i <= maxHorizonCount; i++) {
                cboHorCus.addItem(i);
            }
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_cboHorMinActionPerformed

    private void cboVerMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVerMinActionPerformed
        try {
            cboVerCus.removeAllItems();
            Integer verticalMin = Integer.parseInt(this.cboVerMin.getSelectedItem().toString());
            for (int i = verticalMin; i <= maxVerticalCount; i += 500) {
                cboVerCus.addItem(i);
            }
        } catch (Exception ex) {
            logger.error(ex);
        }

    }//GEN-LAST:event_cboVerMinActionPerformed

    private void cboVerCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVerCusActionPerformed
        isShowing = false;
        
    }//GEN-LAST:event_cboVerCusActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cboHorCus;
    private javax.swing.JComboBox cboHorMin;
    private javax.swing.JComboBox cboVerCus;
    private javax.swing.JComboBox cboVerMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
