/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.adsb.client.gui.targetEditor;

import com.attech.adsb.client.common.MLogger;
import com.attech.adsb.client.common.MouseContext;
import com.attech.adsb.client.common.Target;
import com.attech.adsb.client.common.enums.MouseMode;
import com.attech.adsb.client.config.Point2f;
import com.attech.adsb.client.graphic.Convertor;
import com.attech.adsb.client.gui.customDraw.ICoordinateUsage;

/**
 *
 * @author andh
 */
public class TargetEditor extends javax.swing.JDialog  implements ICoordinateUsage {

    private static final MLogger logger = MLogger.getLogger(TargetEditor.class);
    
    private Target target;
    
    /**
     * Creates new form TargetEditor
     */
    public TargetEditor(java.awt.Frame parent, boolean modal, Target target) {
        super(parent, modal);
        initComponents();
        bind(target);
        this.target = target;
    }
    
    
    private void bind(Target target) {
        this.txtCallsign.setText(target.getCallSign());
        this.txtLevel.setText(Float.toString(target.getFlightLevel()));
        this.txtLongtitude.setText(Double.toString(target.getLongtitude()));
        this.txtLatitude.setText(Double.toString(target.getLatitude()));
        this.txtHeading.setText(Double.toString(target.getHeading()));
        this.txtSpeed.setText(Double.toString(target.getSpeed()));
        this.txtNIC.setText(Integer.toString(target.getNic()));
        this.txtNAC.setText(Integer.toString(target.getNac()));
        this.txtSIL.setText(Integer.toString(target.getSil()));
        this.txtStatus.setText(Integer.toString(target.getTargetStatus()));
    }
    
    private void bind(Point2f point) {
        Point2f wgs84Point = Convertor.fromOpenglToWgs84(point);
        this.txtLongtitude.setText(Double.toString(wgs84Point.getLongtitude()));
        this.txtLatitude.setText(Double.toString(wgs84Point.getLatitude()));
//        Wgs84Coordinate longtitude = Convertor.fromDecimalToWgs84Coord(wgs84Point.getLongtitude());
//        txtLonDeg.setText(Integer.toString(longtitude.getDeg()));
//        txtLonMin.setText(Integer.toString(longtitude.getMin()));
//        txtLonSec.setText(Integer.toString(longtitude.getSec()));
//        chkLonChar.setSelectedItem(longtitude.getLontitudeCharacter());
//
//        Wgs84Coordinate latitude = Convertor.fromDecimalToWgs84Coord(wgs84Point.getLatitude());
//        txtLatDeg.setText(Integer.toString(latitude.getDeg()));
//        txtLatMin.setText(Integer.toString(latitude.getMin()));
//        txtLatSec.setText(Integer.toString(latitude.getSec()));
//        chkLatChar.setSelectedItem(latitude.getLatitdeCharacter());
    }
    
        @Override
    public void updateCoordinate(Point2f point) {
        bind(point);
    }

    @Override
    public void captureCoordinate(Point2f point) {
        bind(point);
        MouseContext.instance().setMode(MouseMode.Normal);
        btnMouseCapture.setSelected(false);
    }

    @Override
    public boolean isAvailable() {
        return this.isVisible();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCallsign = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLongtitude = new javax.swing.JTextField();
        txtLatitude = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnMouseCapture = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtHeading = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSpeed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNAC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSIL = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("CallSign:");

        txtCallsign.setEditable(false);

        jLabel2.setText("Flight Level");

        jLabel3.setText("Longtitude");

        jLabel4.setText("Latitude");

        btnClose.setText("Close");

        btnOK.setText("Apply");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnMouseCapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/adsb/client/images/cursor.png"))); // NOI18N
        btnMouseCapture.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMouseCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMouseCaptureActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");

        jLabel5.setText("Heading");

        jLabel6.setText("Speed");

        jLabel7.setText("NIC");

        jLabel8.setText("NAC");

        jLabel9.setText("SIL");

        jLabel10.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMouseCapture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNAC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSIL, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(188, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(btnOK)
                        .addComponent(jButton1))
                    .addComponent(btnMouseCapture, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMouseCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMouseCaptureActionPerformed
        try {
            logger.info("btnMouseCapture is clicked");
            
            MouseContext.instance().setCoordinateCapptureRequester(this);
//            if (btnMouseCapture.isSelected()) {
//                MouseContext.instance().setMode(MouseMode.Capture);
//            } else if (MouseContext.instance().getMode() == MouseMode.Capture) {
//                MouseContext.instance().setMode(MouseMode.Normal);
//            }
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnMouseCaptureActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.target.setFlightLevel(Float.parseFloat(txtLevel.getText()));
        this.target.setLatitude(Double.parseDouble(txtLatitude.getText()));
        this.target.setLongtitude(Double.parseDouble(txtLongtitude.getText()));
        target.setHeading(Double.parseDouble(txtHeading.getText()));
        target.setSpeed(Double.parseDouble(txtSpeed.getText()));
        target.setNic(Integer.parseInt(txtNIC.getText()));
        target.setNac(Integer.parseInt(txtNAC.getText()));
        target.setSil(Integer.parseInt(txtSIL.getText()));
        target.setTargetStatus(Integer.parseInt(txtStatus.getText()));
       
        this.target.calculate();
        this.target.commitChange(true);
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JToggleButton btnMouseCapture;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCallsign;
    private javax.swing.JTextField txtHeading;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtLongtitude;
    private javax.swing.JTextField txtNAC;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtSIL;
    private javax.swing.JTextField txtSpeed;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
