/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.adsb.client.gui.filter;

import com.attech.adsb.client.config.Configuration;
import com.attech.adsb.client.config.FilterCondition;
import com.attech.adsb.client.graphic.objects.TargetGraphic;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.*;

/**
 *
 * @author NhuongND
 */
public class TargetFilterDlg extends javax.swing.JDialog {


    public static boolean isShowing;
    private JFrame parent;
    private final FilterCondition filterCondition;
    private final DecimalFormat format = new DecimalFormat("#");
    private DialogNotify notify;
    private final Color normalColor;
    private final TargetGraphic targetGraphic;
    
    /**
     * Creates new form SelectFilter
     * @param parent
     * @param modal
     */
    public TargetFilterDlg(JFrame parent, boolean modal, TargetGraphic graphic) {
        super(parent, modal);
        initComponents();
        setDocumentFilter(txtLow);
        setDocumentFilter(txtHight);
        normalColor = txtHight.getBackground();
        
        this.targetGraphic = graphic;
        this.filterCondition = graphic.getFilterCondition();
        this.bind(filterCondition);
    }
    
    private void setDocumentFilter(JTextField textField) {
        AbstractDocument document = (AbstractDocument) textField.getDocument();
        document.setDocumentFilter(new DocumentInputFilter());
    }
    
    private void bind(FilterCondition condition) {
        if (condition.getAltitudeLow() != null) {
            txtLow.setText(format.format(condition.getAltitudeLow()));
        }
        
        if (condition.getAltitudeHigh() != null) {
             txtHight.setText(format.format(filterCondition.getAltitudeHigh()));
        }
        txtCallsign.setText(filterCondition.getCallSign());
        chkActive.setSelected(filterCondition.isActive());
        chkHideLabel.setSelected(filterCondition.isHideTarget());
        chkHideTarget.setSelected(!filterCondition.isHideTarget());
    }
    
    private FilterCondition parse() {
        FilterCondition condition = new FilterCondition();
        condition.setActive(chkActive.isSelected());
        if (txtHight.getText() != null && !txtHight.getText().isEmpty()) {
            condition.setAltitudeHigh(Integer.parseInt(txtHight.getText()));
        }
        if (txtLow.getText() != null && !txtLow.getText().isEmpty()) {
            condition.setAltitudeLow(Integer.parseInt(txtLow.getText()));
        }

        condition.setCallSign(txtCallsign.getText());
        condition.setHideTarget(chkHideTarget.isSelected());
        return condition;
    }
    
    private boolean validateForm() {
        
        txtHight.setBackground(normalColor);
        String altitudeLow = txtLow.getText();
        if (altitudeLow == null || altitudeLow.isEmpty()) {
            return true;
        }
        String altitudeHigh = txtHight.getText();
        if (altitudeHigh == null || altitudeHigh.isEmpty()) {
            return true;
        }
   
        int low = Integer.parseInt(txtLow.getText());
        int high = Integer.parseInt(txtHight.getText());
        
        if (low >= high) {
            txtHight.setBackground(Color.red);
            txtHight.requestFocus();
            txtHight.selectAll();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        chkActive = new javax.swing.JCheckBox();
        btnPreview = new javax.swing.JButton();
        chkHideTarget = new javax.swing.JRadioButton();
        chkHideLabel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtHight = new javax.swing.JTextField();
        txtLow = new javax.swing.JTextField();
        lblLowft = new javax.swing.JLabel();
        txtCallsign = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter Target");
        setMinimumSize(new java.awt.Dimension(400, 155));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.setToolTipText("");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        chkActive.setText("Active");

        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkHideTarget);
        chkHideTarget.setSelected(true);
        chkHideTarget.setText("Hide target");

        buttonGroup1.add(chkHideLabel);
        chkHideLabel.setText("Hide label");

        jLabel2.setText("Altitude");

        txtHight.setMaximumSize(new java.awt.Dimension(100, 24));
        txtHight.setMinimumSize(new java.awt.Dimension(100, 24));
        txtHight.setPreferredSize(new java.awt.Dimension(100, 24));
        txtHight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHightKeyTyped(evt);
            }
        });

        txtLow.setMaximumSize(new java.awt.Dimension(100, 24));
        txtLow.setMinimumSize(new java.awt.Dimension(100, 24));
        txtLow.setPreferredSize(new java.awt.Dimension(100, 24));

        lblLowft.setText("00 ft");

        txtCallsign.setMinimumSize(new java.awt.Dimension(64, 24));
        txtCallsign.setPreferredSize(new java.awt.Dimension(64, 24));

        jLabel6.setText("Callsign");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkActive)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkHideTarget)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkHideLabel)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCallsign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLowft)
                        .addGap(77, 77, 77)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLowft)
                    .addComponent(jLabel1)
                    .addComponent(txtLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkActive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHideTarget)
                    .addComponent(chkHideLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnPreview)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            this.targetGraphic.applyFilter(Configuration.instance().getGraphic().getFilterCondition());
            this.dispose();
        } catch (Exception ex) {

        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {

            if (!this.validateForm()) {
                return;
            }
            
            int confirmed = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to save?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (confirmed != JOptionPane.YES_OPTION) {
                return;
            }
            

            FilterCondition condition = parse();
            this.targetGraphic.applyFilter(condition);
            Configuration.instance().getGraphic().setFilterCondition(condition);
            Configuration.instance().getGraphic().save();
            this.dispose();
            
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        try {
            if (!this.validateForm()) {
                return;
            }

            FilterCondition condition = this.parse();
            this.targetGraphic.applyFilter(condition);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void txtHightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHightKeyTyped
        //int high = Integer.parseInt(txtHight.getText());
        //lblHightft.setText(Integer.toString(high * 100) + " ft");
    }//GEN-LAST:event_txtHightKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // this.parent.setFocusableWindowState(false);
    }//GEN-LAST:event_formComponentShown

    @Override
    public void setVisible(boolean value) {
        isShowing = value;
        super.setVisible(value);
    }
    
    
    /**
     * @param notify the notify to set
     */
    public void setNotify(DialogNotify notify) {
        this.notify = notify;
    }
    
    public void notify(InformType type, Object param) {
        if (this.notify == null) return;
        this.notify.dialogActionPerformed(type, param);
    }
    /*
    class DocumentInputFilter extends DocumentFilter {

        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet as) throws BadLocationException {
            int len = text.length();
            if (len > 0) {

                if (Character.isDigit(text.charAt(len - 1))) {
                    super.insertString(fb, offset, text, as);
                }

            }
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet as) throws BadLocationException {
            int len = text.length();
            if (len > 0) {
                if (Character.isDigit(text.charAt(len - 1))) {
                    super.replace(fb, offset, length, text, as);
                }

            }
        }
    }

    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPreview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JRadioButton chkHideLabel;
    private javax.swing.JRadioButton chkHideTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLowft;
    private javax.swing.JTextField txtCallsign;
    public static javax.swing.JTextField txtHight;
    public static javax.swing.JTextField txtLow;
    // End of variables declaration//GEN-END:variables
}
