/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.asd.administrator.views;

import com.attech.asd.administrator.XmlSerializer;
import com.attech.asd.administrator.common.CustomDialog;
import com.attech.asd.administrator.common.GroundStation;
import com.attech.asd.administrator.common.GroundStationConfig;
import com.attech.asd.administrator.common.Label;
import com.attech.asd.administrator.common.Validator;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author AnhTH
 */
public class AddPoint extends CustomDialog {

    private GroundStationConfig pointConfig;
    private int index; // <0 new; >= 0 edit
    //private int typeIndex; //0 = vor, 1=ndb, 2=fixed point 
    private String[] color = {"#FF00FF", "#000000" , "#FF00FF"};
    private int[] size = {16, 16, 9};

    /**
     * Creates new form ReceiverDialog
     *
     * @param parent
     * @param modal
     * @param handle
     */
    public AddPoint(java.awt.Frame parent, boolean modal, int typeIndex, int index) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        txtLongitude.setDocument(new JTextFieldLimit(9));
        txtLatitude.setDocument(new JTextFieldLimit(8));
        this.index = index;
        //this.typeIndex = typeIndex;
        cmbType.setSelectedIndex(typeIndex);
        cmbType.setEnabled(this.index < 0);
        binding();
    }

    private void binding() {
        switch (cmbType.getSelectedItem().toString()){
            case "VOR/DME":
                pointConfig = XmlSerializer.load("res/vor-dme.xml", GroundStationConfig.class);
                break;
            case "NDB":
                pointConfig = XmlSerializer.load("res/ndb.xml", GroundStationConfig.class);
                break;
            case "FIXED-POINT":
                pointConfig = XmlSerializer.load("res/fix-point.xml", GroundStationConfig.class);
                break;
        }
        
        if (index >= 0) {
            this.txtLatitude.setText(String.format("%s", pointConfig.getGroundStations().get(index).getY()));
            this.txtLongitude.setText(String.format("%s", pointConfig.getGroundStations().get(index).getX()));
            this.txtName.setText(String.format("%s", pointConfig.getGroundStations().get(index).getName()));
        } else {
            this.txtName.setText(String.format(""));
            this.txtLatitude.setText(String.format(""));
            this.txtLongitude.setText(String.format(""));
        }
    }

    private boolean validated() {
        if (!Validator.isEmpty(String.format(txtName.getText()), 1)) {
            JOptionPane.showMessageDialog(rootPane, String.format("Check input value!"));
            txtName.requestFocus();
            return false;
        }
        if (!Validator.isNumberic(String.format(txtLatitude.getText()))) {
            JOptionPane.showMessageDialog(rootPane, String.format("Check input value!"));
            txtLatitude.requestFocus();
            return false;
        }
        if (!Validator.isNumberic(String.format(txtLongitude.getText()))) {
            JOptionPane.showMessageDialog(rootPane, String.format("Check input value!"));
            txtLongitude.requestFocus();
            return false;
        }
        float lat = Float.parseFloat(txtLatitude.getText().trim());
        if (lat > 90f || lat < -90f) {
            txtLatitude.requestFocus();
            return false;
        }
        float lon = Float.parseFloat(txtLongitude.getText().trim());
        if (lon > 180f || lon < -180f) {
            txtLongitude.requestFocus();
            return false;
        }
        
            //validate name unique
            
        for (int i = 0; i < pointConfig.getGroundStations().size(); i++){
            if (i == index)
                continue;
            if (pointConfig.getGroundStations().get(i).getName().equals(txtName.getText().trim().toUpperCase())){
                JOptionPane.showMessageDialog(rootPane, String.format("Name exist. Try another!"));
                txtName.requestFocus();
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        txtLatitude = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Point -  ADSB Administrator Terminal 1.0.0");
        setResizable(false);

        jLabel4.setText("Name");

        jLabel9.setText("Longitude");

        jLabel13.setText("Latitude");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/door_out.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel14.setText("Type");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VOR/DME", "NDB", "FIXED-POINT" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLatitude, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbType, 0, 204, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
        if (!validated()) {
            return;
        }
        if (index < 0){
            GroundStation obj = new GroundStation();
            obj.setName(txtName.getText().trim().toUpperCase());
            obj.setEnabled(true);
            obj.setX(Float.parseFloat(txtLongitude.getText().trim()));
            obj.setY(Float.parseFloat(txtLatitude.getText().trim()));
            obj.setColor(color[cmbType.getSelectedIndex()]);
            obj.setSize(size[cmbType.getSelectedIndex()]);
            obj.setWeight(1);
            obj.setzIndex(100.0f);
            Label label = new Label(pointConfig.getGroundStations().get(0).getLabel());
            label.setContent(obj.getName());
            obj.setLabel(label);
            pointConfig.getGroundStations().add(obj);
        } else {
            pointConfig.getGroundStations().get(index).setName(txtName.getText().trim().toUpperCase());
            pointConfig.getGroundStations().get(index).setX(Float.parseFloat(txtLongitude.getText().trim()));
            pointConfig.getGroundStations().get(index).setY(Float.parseFloat(txtLatitude.getText().trim()));
            pointConfig.getGroundStations().get(index).getLabel().setContent(txtName.getText().trim().toUpperCase());
        }
        switch (cmbType.getSelectedItem().toString()){
            case "VOR/DME":
                XmlSerializer.serialize("res/vor-dme.xml", pointConfig);
                break;
            case "NDB":
                XmlSerializer.serialize("res/ndb.xml", pointConfig);
                break;
            case "FIXED-POINT":
                XmlSerializer.serialize("res/fix-point.xml", pointConfig);
                break;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Successfully!");
        this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } finally {
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        binding();
    }//GEN-LAST:event_cmbTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
