/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.asd.administrator.views;

import com.attech.asd.administrator.XmlSerializer;
import com.attech.asd.administrator.common.CustomDialog;
import com.attech.asd.administrator.common.RouteLine;
import com.attech.asd.administrator.common.RoutesConfig;
import com.attech.asd.administrator.common.Validator;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author AnhTH
 */
public class AddRoute extends CustomDialog {

    private RoutesConfig routeConfig;
    private int index; // <0 new; >= 0 edit
    /**
     * Creates new form ReceiverDialog
     *
     * @param parent
     * @param modal
     * @param handle
     */
    public AddRoute(java.awt.Frame parent, boolean modal, int index) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.index = index;
        binding();
    }

    private void binding() {
        routeConfig = XmlSerializer.load("res/routes.xml", RoutesConfig.class);
        routeConfig.loadDefendency();
        bindPointCombo();
        if (index >= 0) { // edit
            this.txtPoints.setText(String.format("%s", routeConfig.getLines().get(index).getPoints().stream().map(Object::toString).collect(Collectors.joining(", "))));
            this.txtName.setText(String.format("%s", routeConfig.getLines().get(index).getName()));
        } else {
            this.txtName.setText(String.format(""));
            this.txtPoints.setText(String.format(""));
        }
    }

    private boolean validated() {
        if (!Validator.isEmpty(String.format(txtName.getText()), 1)) {
            JOptionPane.showMessageDialog(rootPane, String.format("Check input value!"));
            txtName.requestFocus();
            return false;
        }
        if (!Validator.isEmpty(String.format(txtPoints.getText()))) {
            JOptionPane.showMessageDialog(rootPane, String.format("Check input value!"));
            txtPoints.requestFocus();
            return false;
        }
        for (int i = 0; i < routeConfig.getLines().size(); i++){
            if (i == index)
                continue;
            RouteLine obj = routeConfig.getLines().get(i);
            if (obj.getName().equals(txtName.getText().trim().toUpperCase())){
                JOptionPane.showMessageDialog(rootPane, String.format("Name exist. Try another!"));
                txtName.requestFocus();
                return false;
            }
        }
        
        String [] tmp = txtPoints.getText().split(", ");
        for (String s: tmp){
            if (!routeConfig.getListPoint().contains(s)){
                JOptionPane.showMessageDialog(rootPane, String.format("Point %s not exist.!", s));
                txtName.requestFocus();
                return false;
            }
        }
        
        return true;
    }
    
    private void bindPointCombo(){
        cmbPoint.removeAllItems();
        for (String s : routeConfig.getListPoint()) {
            cmbPoint.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPoints = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbPoint = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Route -  ADSB Administrator Terminal 1.0.0");
        setResizable(false);

        jLabel4.setText("Name");

        jLabel9.setText("Points");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/door_out.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel14.setText("Points List");

        cmbPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Select ---" }));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/add_16.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPoints, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
        if (!validated()) {
            return;
        }
        if (index < 0){ // add new
            RouteLine obj = new RouteLine(routeConfig.getLines().get(0));
            obj.setName(txtName.getText().trim().toUpperCase());
            obj.getLabel().setContent(obj.getName());
            obj.setPoints(Arrays.asList(txtPoints.getText().trim().split(", ")));
            routeConfig.addLine(obj);
        } else {
            routeConfig.getLines().get(index).setName(txtName.getText().trim().toUpperCase());
            routeConfig.getLines().get(index).getLabel().setContent(txtName.getText().trim().toUpperCase());
            routeConfig.getLines().get(index).setPoints(Arrays.asList(txtPoints.getText().trim().split(", ")));
        }
        
        XmlSerializer.serialize("res/routes.xml", routeConfig);
        JOptionPane.showMessageDialog(rootPane, "Successfully!");
        this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } finally {
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtPoints.setText(txtPoints.getText().trim());
        if (txtPoints.getText().isEmpty())
            txtPoints.setText(cmbPoint.getSelectedItem().toString());
        else
            txtPoints.setText(String.format("%s, %s",txtPoints.getText(), cmbPoint.getSelectedItem()));
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPoint;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPoints;
    // End of variables declaration//GEN-END:variables

}
