/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.asd.administrator.views;

import com.attech.asd.administrator.XmlSerializer;
import com.attech.asd.administrator.common.CellRender;
import com.attech.asd.administrator.common.CustomDialog;
import com.attech.asd.administrator.common.GroundStationConfig;
import com.attech.asd.administrator.common.NormalTableModel;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author anhth
 */
public class PointsDialog extends CustomDialog {

    private final NormalTableModel tableModel;
    public final static String COL_NO = "#";
    public final static String COL_NAME = "NAME";
    public final static String COL_LNG = "LONGITUDE";
    public final static String COL_LAT = "LATITUDE";

    private GroundStationConfig pointConfig;

    /**
     * Creates new form PointsDialog
     *
     * @param parent
     * @param modal
     * @param points
     */
    public PointsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.tableModel = new NormalTableModel(tblPoints);
        this.tableModel.addColumn(COL_NO);
        this.tableModel.addColumn(COL_NAME);
        this.tableModel.addColumn(COL_LNG);
        this.tableModel.addColumn(COL_LAT);


        setColumnWidth(this.tblPoints, COL_NO, 50, 50, 50);
        setColumnWidth(this.tblPoints, COL_LNG, 80, 100, 100);
        setColumnWidth(this.tblPoints, COL_LAT, 80, 100, 100);

        this.tblPoints.setDefaultRenderer(Integer.class, new CellRender());
        this.tblPoints.setDefaultRenderer(String.class, new CellRender());
        this.tblPoints.setDefaultRenderer(Float.class, new CellRender());
        this.tblPoints.setDefaultRenderer(Float.class, new CellRender());

        binding();
    }

    private void binding() {
        switch (cmbType.getSelectedItem().toString()) {
            case "VOR/DME":
                pointConfig = XmlSerializer.load("res/vor-dme.xml", GroundStationConfig.class);
                break;
            case "NDB":
                pointConfig = XmlSerializer.load("res/ndb.xml", GroundStationConfig.class);
                break;
            case "FIXED-POINT":
                pointConfig = XmlSerializer.load("res/fix-point.xml", GroundStationConfig.class);
                break;
        }
        tableModel.setNumRows(0);
        for (int i = 0; i < pointConfig.getGroundStations().size(); i++) {
            this.tableModel.addRow(new Object[]{(i + 1), pointConfig.getGroundStations().get(i).getName(), pointConfig.getGroundStations().get(i).getX(), pointConfig.getGroundStations().get(i).getY()});
        }
    }

    private void setColumnWidth(JTable table, String name, int min, int max, int prefer) {
        table.getColumn(name).setMinWidth(min);
        table.getColumn(name).setMaxWidth(max);
        table.getColumn(name).setPreferredWidth(prefer);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoints = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Points -  ADSB Administrator Terminal 1.0.0");
        setResizable(false);

        tblPoints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPointsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoints);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/door_out.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VOR/DME", "NDB", "FIXED-POINT" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/delete1.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/add_16.png"))); // NOI18N
        btnAdd.setText("New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(178, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        binding();
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (tblPoints.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "You must select one report", "Form validation", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        final int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure ?");
        if (result != JOptionPane.YES_OPTION) {
            return;
        }
        int index = tblPoints.getSelectedRow();
        pointConfig.getGroundStations().remove(index);
        switch (cmbType.getSelectedItem().toString()){
            case "VOR/DME":
                XmlSerializer.serialize("res/vor-dme.xml", pointConfig);
                break;
            case "NDB":
                XmlSerializer.serialize("res/ndb.xml", pointConfig);
                break;
            case "FIXED-POINT":
                XmlSerializer.serialize("res/fix-point.xml", pointConfig);
                break;
        }
        binding();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddPoint dialog = new AddPoint(null, true, cmbType.getSelectedIndex(), -1);
        dialog.setVisible(true);
        binding();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblPointsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPointsMousePressed
        if (evt.getButton() != 1) {
            return;
        }
        JTable table = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int index = table.rowAtPoint(p);
        if (evt.getClickCount() != 2) {
            return;
        }
        AddPoint dialog = new AddPoint(null, true, cmbType.getSelectedIndex(), index);
        dialog.setVisible(true);
        binding();
    }//GEN-LAST:event_tblPointsMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPoints;
    // End of variables declaration//GEN-END:variables
}
