/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.asd.administrator.views;

import com.attech.asd.administrator.XmlSerializer;
import com.attech.asd.administrator.common.CellRender;
import com.attech.asd.administrator.common.CustomDialog;
import com.attech.asd.administrator.common.NormalTableModel;
import com.attech.asd.administrator.common.RouteLine;
import com.attech.asd.administrator.common.RoutesConfig;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.stream.Collectors;

/**
 *
 * @author anhth
 */
public class RouteDialog extends CustomDialog {

    private final NormalTableModel tableModel;
    public final static String COL_NO = "#";
    public final static String COL_NAME = "NAME";
    public final static String COL_POINT = "POINT";

    private RoutesConfig routeConfig;

    /**
     * Creates new form PointsDialog
     *
     * @param parent
     * @param modal
     * @param points
     */
    public RouteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.tableModel = new NormalTableModel(tblPoints);
        this.tableModel.addColumn(COL_NO);
        this.tableModel.addColumn(COL_NAME);
        this.tableModel.addColumn(COL_POINT);


        setColumnWidth(this.tblPoints, COL_NO, 50, 50, 50);
        setColumnWidth(this.tblPoints, COL_NAME, 70, 70, 70);

        this.tblPoints.setDefaultRenderer(Integer.class, new CellRender());
        this.tblPoints.setDefaultRenderer(String.class, new CellRender());
        this.tblPoints.setDefaultRenderer(String.class, new CellRender());

        binding();
    }

    private void binding() {
        routeConfig = XmlSerializer.load("res/routes.xml", RoutesConfig.class);
        routeConfig.loadDefendency();
        
        tableModel.setNumRows(0);
        
        
        for (int i = 0; i < routeConfig.getLines().size(); i++) {
            RouteLine obj = routeConfig.getLines().get(i);
            //final String listPoint = obj.getPoints().stream().map(Object::toString).collect(Collectors.joining(","));
            this.tableModel.addRow(new Object[]{(i + 1), obj.getName(), obj.getPoints().stream().map(Object::toString).collect(Collectors.joining(", "))});
        }
        
    }

    private void setColumnWidth(JTable table, String name, int min, int max, int prefer) {
        table.getColumn(name).setMinWidth(min);
        table.getColumn(name).setMaxWidth(max);
        table.getColumn(name).setPreferredWidth(prefer);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoints = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Routes -  ADSB Administrator Terminal 1.0.0");
        setResizable(false);

        tblPoints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPointsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoints);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/door_out.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/delete1.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/attech/asd/administrator/images/add_16.png"))); // NOI18N
        btnAdd.setText("New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (tblPoints.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "You must select one report", "Form validation", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        final int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure ?");
        if (result != JOptionPane.YES_OPTION) {
            return;
        }
        int index = tblPoints.getSelectedRow();
        routeConfig.getLines().remove(index);
        XmlSerializer.serialize("res/routes.xml", routeConfig);
        binding();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddRoute dialog = new AddRoute(null, true, -1);
        dialog.setVisible(true);
        binding();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblPointsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPointsMousePressed
        if (evt.getButton() != 1) {
            return;
        }
        JTable table = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int index = table.rowAtPoint(p);
        if (evt.getClickCount() != 2) {
            return;
        }
        AddRoute dialog = new AddRoute(null, true, index);
        dialog.setVisible(true);
        binding();
    }//GEN-LAST:event_tblPointsMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPoints;
    // End of variables declaration//GEN-END:variables
}
