/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.attech.adsb.client.gui.mapSetup;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author dungnt
 */
public class MapBackgroundChangerDlg extends JDialog {

    /**
     * @return the dialogResult
     */
    public int getDialogResult() {
        return dialogResult;
    }

    private static final Logger logger = Logger.getLogger(MapBackgroundChangerDlg.class);
    
    /**
     * @return the color
     */
    public String getColor() {
        return color;
    }

    /**
     * @param color the color to set
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * @param colorChangeNotify the colorChangeNotify to set
     */
    public void setColorChangeNotify(ColorChangeNotify colorChangeNotify) {
        this.colorChangeNotify = colorChangeNotify;
    }

     private int dialogResult;
     private ColorChangeNotify colorChangeNotify;
     private String color;
     
    public static int ColorRed = 138;
    public static int ColorGreen = 138;
    public static int ColorBlue = 138;
    public static boolean isShowing;
    
    /**
     * Creates new form SelectMapSetup
     * @param parent
     * @param modal
     */
    public MapBackgroundChangerDlg(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.dialogResult = JOptionPane.CANCEL_OPTION;
//        colorRed.setValue(ColorRed);
//        colorGreen.setValue(ColorGreen);
//        colorBlue.setValue(ColorBlue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        btnColorChooser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Background Color Chooser");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(400, 240));
        setMinimumSize(new java.awt.Dimension(400, 240));
        setPreferredSize(new java.awt.Dimension(400, 240));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnColorChooser.setToolTipText("");
        btnColorChooser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColorChooser.setContentAreaFilled(false);
        btnColorChooser.setMaximumSize(new java.awt.Dimension(50, 26));
        btnColorChooser.setMinimumSize(new java.awt.Dimension(50, 26));
        btnColorChooser.setPreferredSize(new java.awt.Dimension(50, 26));
        btnColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorChooserActionPerformed(evt);
            }
        });

        jLabel4.setText("Background color:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(btnColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(btnColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk)
                    .addComponent(btnPreview))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            if (this.colorChangeNotify == null) {
                return;
            }
            this.colorChangeNotify.colorChanged(JOptionPane.CANCEL_OPTION, color);
        } catch (Exception ex) {
            logger.error(ex);
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            if (this.colorChangeNotify == null) {
                return;
            }
            
            int confirmed = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to save?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (confirmed != JOptionPane.YES_OPTION) {
                return;
            }
            this.colorChangeNotify.colorChanged(JOptionPane.OK_OPTION, color);
        } catch (Exception ex) {
            logger.error(ex);
        } finally {
            this.dispose();
        }

        //this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        isShowing = false;
    }//GEN-LAST:event_formWindowClosed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        try {
            if (this.colorChangeNotify == null) {
                return;
            }
            this.colorChangeNotify.colorChanged(JOptionPane.CLOSED_OPTION, color);
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            this.btnColorChooser.setBackground(Color.decode(this.color));
            this.btnColorChooser.setOpaque(true);
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorChooserActionPerformed
        try {
            JButton colorButton = (JButton) evt.getSource();
            Color curretColor = colorButton.getBackground();
            Color selectedColor = JColorChooser.showDialog(this, "Select a color", curretColor);
            if (selectedColor == null) return;
            colorButton.setBackground(selectedColor);
            colorButton.setContentAreaFilled(false);
            colorButton.setOpaque(true);
            this.color = String.format("#%02x%02x%02x", selectedColor.getRed(), selectedColor.getGreen(), selectedColor.getBlue()).toUpperCase();

        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_btnColorChooserActionPerformed

    
    @Override
    public void setVisible(boolean value) {
        isShowing = value;
        super.setVisible(value);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnColorChooser;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPreview;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
